---
version: "3"
services:
  flowcyto:
    image: gnasello/flowcyto-env:2023-10-31
    container_name: flowcyto-env
    security_opt:
      - seccomp:unconfined # for terminal to work
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      #- SUBFOLDER=/ #optional
    ports:
      - 3000:3000
    #devices:
      #- /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional